### ISSUE TITLE
Fresh install fails without DBI and assertthat packages

### ISSUE THREAD

**Issue by ConorIA** [gavinsimpson/canadaHCD#12]
Hi Gavin, 

I just tried installing on a fresh lab computer (i.e. on a fresh library). The install fails complaining that DBI and assertthat are missing. I thought to send a PR, but wasn't sure whether these would be imports or dependencies, so I thought I'd ping you first.

Cheers

**Comment by gavinsimpson** [comment]
It seems this is coming from our importing of the **dplyr** package. I need to check again, but with changes in **tibble** we may not need **dplyr** any longer. Either way, I don't think this is an issue with **canadaHCD** unless we are specifically using functionality from those packages; installing **dplyr** should have ensured that the stated packages were installed as those are dependencies of **dplyr**.

**Comment by gavinsimpson** [comment]
We can't remove the dependency on **dplyr** until equivalent `dplyr::bind_rows()` functionality is available in **tibble** but that may be some time off, see tidyverse/tibble#34.

**Comment by ConorIA** [comment]
I have just installed _canadaHCD_ on a very minimal R implementation on Linux (via Docker - specifically https://github.com/ConorIA/dockerfiles/tree/master/alpine-r). There was no such issue. Not sure why I had trouble on Windows but not on Linux (I should mention that I have always used Linux before now, and never had any issue installing _canadaHCD_). At any rate, this doesn't seem to be _canadaHCD_'s fault, so I will go ahead and close this issue.
