### ISSUE TITLE
Licenses are inconsistent

### ISSUE THREAD

**Issue by ConorIA** [gavinsimpson/canadaHCD#17]
Just thought I'd point out that the license in `LICENSE` is the GPLv3, but the description of the package lists the license as the GPLv2. Cheers.

**Comment by gavinsimpson** [comment]
@ConorIA Thanks for pointing that out: I think this is a copy-paste error on my part.

As you and I are the only copyright holders do you have any objection to me changing the `Licence` tag in `DESCRIPTION` to be consistent with the `LICENSE` file to the extent that the pkg is licensed GPLv3?

**Comment by ConorIA** [comment]
None at all!
