### ISSUE TITLE
hcd_hourly(6358, 2017, 9) gives error in creating clean names

### ISSUE THREAD

**Issue by dankelley** [gavinsimpson/canadaHCD#22]
I get an error as at PART 2 below. I think the data files from env-can must no longer give the quality-control data that you were assuming, in naming `df`.  PART 1 is a crude patch, although I suppose it would be more sensible to check on the existing names, not just their count.

It is *such* a pain dealing with data in changing formats.  I really appreciate the work you've done with canadaHCD.

PART 1

[patch.txt](https://github.com/gavinsimpson/canadaHCD/files/1976895/patch.txt)

PART 2

```R
> library(canadaHCD)
> d <- hcd_hourly(6358, 2017, 9)
  |                                                                                                                       |   0%Parsed with column specification:
cols(
  .default = col_character(),
  `Date/Time` = col_datetime(format = ""),
  Year = col_integer(),
  Time = col_time(format = "")
)
See spec(...) for full column specifications.
Error in names(df) <- if (inherits(df[[1]], "Date")) { : 
  'names' attribute [21] must be the same length as the vector [20]

> traceback()
6: read_hcd(f, ...) at get_hcd_from_url.R#5
5: withCallingHandlers(expr, warning = handler) at capture_warnings.R#7
4: capture_warnings(read_hcd(f, ...)) at get_hcd_from_url.R#5
3: get_hcd_from_url(urls[i], ...) at process_downloads.R#10
2: process_downloads(urls$url, progress = progress, ...) at hcd_hourly.R#20
1: hcd_hourly(6358, 2017, 9)
```

**Comment by gavinsimpson** [comment]
Thanks for reporting this @dankelley and apologies for the slow response time: the day job has been quite demanding of late.

I'll get this fixed in the pkg ASAP - esp as @ConorIA has provided a PR to fix this issue.
