### ISSUE TITLE
hcd_hourly() fails (and its URL might be wrong)

### ISSUE THREAD

**Issue by dankelley** [gavinsimpson/canadaHCD#29]
I think there may be a problem in downloading data, as you can see below.  This seems to relate to a change in how tibbles work.

Actually, it might also be due to a change in the server-query structure.  When I try to download hourly data directly, using the URL it constructs, I get headers without actual data.  (I discovered this because I am getting the same thing in the `oce::download.met()`.  If I figure out the URL problem, I'll post the new pattern here.  No promises on the speed of that, though -- teaching season is upon us.)

Dan.

```R
> library(canadaHCD)
> find_station("Halifax")
# A tibble: 13 × 5
   Name                      Province         StationID LatitudeDD LongitudeDD
   <fct>                     <fct>            <fct>          <dbl>       <dbl>
 1 BABINE LAKE HALIFAX BAY   British Columbia 455             55.0      -126. 
 2 HALIFAX                   Nova Scotia      6355            44.6       -63.6
 3 HALIFAX                   Nova Scotia      6356            44.6       -63.6
 4 HALIFAX CITADEL           Nova Scotia      6357            44.6       -63.6
 5 HALIFAX COMMONS           Nova Scotia      49128           44.6       -63.6
 6 HALIFAX DOCKYARD          Nova Scotia      43405           44.7       -63.6
 7 HALIFAX INTL A            Nova Scotia      53938           44.9       -63.5
 8 HALIFAX STANFIELD INT'L A Nova Scotia      6358            44.9       -63.5
 9 HALIFAX INTL A            Nova Scotia      50620           44.9       -63.5
10 HALIFAX KOOTENAY          Nova Scotia      43124           44.6       -63.6
11 HALIFAX WINDSOR PARK      Nova Scotia      43403           44.7       -63.6
12 HALIFAX RADAR             Nova Scotia      9030            44.9       -63.5
13 HALIFAX METOC             Nova Scotia      10879           44.7       -63.6
> d <- hcd_hourly(6357,2023,09)
Rows: 720 Columns: 30                                                                                    
── Column specification ──────────────────────────────────────────────
Delimiter: ","
chr   (3): Station Name, Month, Day
dbl   (4): Longitude (x), Latitude (y), Climate ID, Year
lgl  (21): Temp (°C), Temp Flag, Dew Point Temp (°C), Dew Point Te...
dttm  (1): Date/Time (LST)
time  (1): Time (LST)

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error:
! Names repair functions can't return `NA` values.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by dankelley** [comment]
Oh, sorry.  I think maybe there is just no data there anymore. I tried another station and another year, as below.  That worked. But if I go to year 2013, there are no data.  So I don't think this is a problem with this package.  I am pretty sure this station is still recording -- it is Halifax, Stanfield Int'l Airport, which I check often for the weather -- but maybe env-can has moved the data provision to a new format.  (Canadian Hydrographic Service has changed its data provision a few months back... but at least they are now using an API, which removes guesswork.)

```
year=2012;curl "https://climate.weather.gc.ca/climate_data/bulk_data_e.html?format=csv&stationID=6358&Year={$year}&Month=1&Day=1&timeframe=1&submit=Download+Data" >dan.csv;head dan.csv
```

**Comment by dankelley** [comment]
I see that station `43405` works for the download, so I'm good to go (using the oce package) but `hcd_hourly()` produces an error with this, as below.

Sorry, Gavin, for the noise in the previous comments.  But I think the snippet below might be of use to you.  When I download the file, it contains data, as expected.  (Also, as expected, the pressure gauge has a problem during the storm and has not recovered.  Well, a lot of NS still doesn't have power so that might be a factor.)

Dan

```R
> hcd_hourly(43405,2023,9)
Rows: 720 Columns: 30                                                                                             
── Column specification ───────────────────────────────────────────────────────
Delimiter: ","
chr   (4): Station Name, Month, Day, Stn Press Flag
dbl  (11): Longitude (x), Latitude (y), Climate ID, Year, Temp (°C), Dew Po...
lgl  (13): Temp Flag, Dew Point Temp Flag, Rel Hum Flag, Precip. Amount (mm...
dttm  (1): Date/Time (LST)
time  (1): Time (LST)

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Error:
! Names repair functions can't return `NA` values.
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by gavinsimpson** [comment]
Thanks @dankelley; seems they changed the format *again*. Your examples work now if you reinstall from GitHub.
